<a href="https://colab.research.google.com/github/aniruddhagalgali/bprim_ai/blob/main/20260711_pandas_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
#Pandas
import pandas as pd   # pandas is the library for working with tables
import numpy as np
import time


from pprint import pprint

In [86]:
# Paste your copied path inside the quotes (usually starts with '/content/')
df = pd.read_csv("/content/shop_sales.csv")
df.head()
df.tail()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      12 non-null     object
 1   city      12 non-null     object
 2   customer  12 non-null     object
 3   units     12 non-null     int64
 4   price     12 non-null     int64
dtypes: int64(2), object(3)
memory usage: 612.0+ bytes

In [87]:
df[["city","units"]]

      city  units
0     Pune     10
1   Mumbai      4
2     Pune      7
3    Delhi      2
4   Mumbai      9
5     Pune      5
6    Delhi      6
7   Mumbai      8
8     Pune      3
9   Mumbai     13
10   Delhi      4
11    Pune      6

In [ ]:
df["city"].unique()

array(['Pune', 'Mumbai', 'Delhi'], dtype=object)

In [ ]:
df["city"].value_counts()

city
Pune      5
Mumbai    4
Delhi     3
Name: count, dtype: int64

In [ ]:
df["city"].value_counts(normalize=True)*100

city
Pune      41.666667
Mumbai    33.333333
Delhi     25.000000
Name: proportion, dtype: float64

In [ ]:
df.iloc[0]

date        2024-01-03
city              Pune
customer          Asha
units               10
price              250
Name: 0, dtype: object

In [ ]:
df.iloc[1:6:2]

         date    city customer  units  price
1  2024-01-05  Mumbai     Ravi      4    300
3  2024-01-08   Delhi     John      2    180
5  2024-01-11    Pune     Asha      5    250

In [ ]:
df[df['city'].isin(["Mumbai","Pune"])]

          date    city customer  units  price
0   2024-01-03    Pune     Asha     10    250
1   2024-01-05  Mumbai     Ravi      4    300
2   2024-01-06    Pune    Meera      7    250
4   2024-01-09  Mumbai     Sara      9    300
5   2024-01-11    Pune     Asha      5    250
7   2024-01-14  Mumbai     Ravi      8    300
8   2024-01-15    Pune    Kiran      3    250
9   2024-01-17  Mumbai     Sara     13    300
11  2024-01-20    Pune    Meera      6    250

In [88]:
df[((df['city']=="Mumbai")|(df['city']=="Pune")) & (df["units"] > 8) ]
df[(df["units"] > 8) | (df["price"]>200)]

          date    city customer  units  price
0   2024-01-03    Pune     Asha     10    250
1   2024-01-05  Mumbai     Ravi      4    300
2   2024-01-06    Pune    Meera      7    250
4   2024-01-09  Mumbai     Sara      9    300
5   2024-01-11    Pune     Asha      5    250
7   2024-01-14  Mumbai     Ravi      8    300
8   2024-01-15    Pune    Kiran      3    250
9   2024-01-17  Mumbai     Sara     13    300
11  2024-01-20    Pune    Meera      6    250

In [ ]:
df.groupby("city")["price"].sum()

city
Delhi      540
Mumbai    1200
Pune      1250
Name: price, dtype: int64

In [ ]:
df["revenue"]=df["units"] * df["price"]
#df
df.groupby("city")[["units","revenue"]].sum()

        units  revenue
city
Delhi      12     2160
Mumbai     34    10200
Pune       31     7750

In [ ]:
df.sort_values("revenue",ascending=False)
df.groupby("city")[["units","revenue"]].sum()

        units  revenue
city
Delhi      12     2160
Mumbai     34    10200
Pune       31     7750

In [ ]:
df.groupby("city")["revenue"].agg(["count","mean","sum"])

        count    mean    sum
city
Delhi       3   720.0   2160
Mumbai      4  2550.0  10200
Pune        5  1550.0   7750

In [ ]:
#df.loc[12]=["2024-01-20",	"Pune",	"Amit",	8,	550]
df.loc[len(df)]=["2024-01-20",	"Pune",	"Anil",	10,	750]
df.loc[len(df)]=["2024-01-20",	"Pune",	"Sunil",	20,	850]
print(df)

ValueError: cannot set a row with mismatched columns

In [ ]:
df_1 = df.iloc[0:5]
df_2 = df.iloc[5:10]
print(df_1)
print(df_2)
df_1.loc[5] = ["2024-02-17",	"Pune",	"Ramesh",	5,	420]
df_1.loc[5] = ["2024-02-11",	"Pune",	"Suresh",	5,	420]
pd.concat([df_1,df_2])
#df.drop(df.index[14],inplace=True)

df

         date    city customer  units  price  revenue
0  2024-01-03    Pune     Asha     10    250     2500
1  2024-01-05  Mumbai     Ravi      4    300     1200
2  2024-01-06    Pune    Meera      7    250     1750
3  2024-01-08   Delhi     John      2    180      360
4  2024-01-09  Mumbai     Sara      9    300     2700
         date    city customer  units  price  revenue
5  2024-01-11    Pune     Asha      5    250     1250
6  2024-01-12   Delhi   Vikram      6    180     1080
7  2024-01-14  Mumbai     Ravi      8    300     2400
8  2024-01-15    Pune    Kiran      3    250      750
9  2024-01-17  Mumbai     Sara     13    300     3900

ValueError: cannot set a row with mismatched columns

In [107]:
#Define tiers as separate table
tiers = pd.DataFrame ({"tier":["gold","silver","bronze","platinum"],"customer": ["Asha","Ravi","Meera",""]})
print(tiers)

#Merge tiers with df
df_3 = pd.merge(df, tiers, how="left", on="customer")
df_3

       tier customer
0      gold     Asha
1    silver     Ravi
2    bronze    Meera
3  platinum

          date    city customer  units  price    tier
0   2024-01-03    Pune     Asha     10    250    gold
1   2024-01-05  Mumbai     Ravi      4    300  silver
2   2024-01-06    Pune    Meera      7    250  bronze
3   2024-01-08   Delhi     John      2    180     NaN
4   2024-01-09  Mumbai     Sara      9    300     NaN
5   2024-01-11    Pune     Asha      5    250    gold
6   2024-01-12   Delhi   Vikram      6    180     NaN
7   2024-01-14  Mumbai     Ravi      8    300  silver
8   2024-01-15    Pune    Kiran      3    250     NaN
9   2024-01-17  Mumbai     Sara     13    300     NaN
10  2024-01-18   Delhi     John      4    180     NaN
11  2024-01-20    Pune    Meera      6    250  bronze

In [109]:
def discount(price):
  if price > 250:
    return price * 0.9
  else:
    return price * 0.95

In [115]:
df["discounted_price"] = df["price"].apply(discount)
df

          date    city customer  units  price  discounted_price
0   2024-01-03    Pune     Asha     10    250             237.5
1   2024-01-05  Mumbai     Ravi      4    300             270.0
2   2024-01-06    Pune    Meera      7    250             237.5
3   2024-01-08   Delhi     John      2    180             171.0
4   2024-01-09  Mumbai     Sara      9    300             270.0
5   2024-01-11    Pune     Asha      5    250             237.5
6   2024-01-12   Delhi   Vikram      6    180             171.0
7   2024-01-14  Mumbai     Ravi      8    300             270.0
8   2024-01-15    Pune    Kiran      3    250             237.5
9   2024-01-17  Mumbai     Sara     13    300             270.0
10  2024-01-18   Delhi     John      4    180             171.0
11  2024-01-20    Pune    Meera      6    250             237.5

In [117]:
df.drop(columns="discounted_price")

          date    city customer  units  price
0   2024-01-03    Pune     Asha     10    250
1   2024-01-05  Mumbai     Ravi      4    300
2   2024-01-06    Pune    Meera      7    250
3   2024-01-08   Delhi     John      2    180
4   2024-01-09  Mumbai     Sara      9    300
5   2024-01-11    Pune     Asha      5    250
6   2024-01-12   Delhi   Vikram      6    180
7   2024-01-14  Mumbai     Ravi      8    300
8   2024-01-15    Pune    Kiran      3    250
9   2024-01-17  Mumbai     Sara     13    300
10  2024-01-18   Delhi     John      4    180
11  2024-01-20    Pune    Meera      6    250

In [133]:
def total_sale(row):
  return row["units"] * row["price"]

In [142]:
# Capture timestamps in integer nanoseconds
start_time = time.time_ns()
#Apply function
df['total_sale'] = df[["units", "price"]].apply(total_sale, axis=1)
end_time = time.time_ns()

# Compute the difference
nanoseconds_elapsed_apply = end_time - start_time
print(f"Time difference: {nanoseconds_elapsed_apply} ns")

Time difference: 3252272 ns

In [143]:
# Capture timestamps in integer nanoseconds
start_time = time.time_ns()
#Vecotorized
df['total_sale'] = df["units"] * df["price"]
end_time = time.time_ns()

# Compute the difference
nanoseconds_elapsed_vectorized = end_time - start_time
print(f"Time difference: {nanoseconds_elapsed_vectorized} ns")

Time difference: 647863 ns

In [152]:
print("Vectorized approach is", round(nanoseconds_elapsed_vectorized/nanoseconds_elapsed_apply*100,2), "% faster than Apply",)

Vectorized approach is 19.92 % faster than Apply

np.int64(1)